<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Home extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
		if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
		{
			redirect('/');
		}

		$this->load->view('home');
     
    } 
    public function dashboard_pd()
    {
        $this->load->view('halaman_pd');
    }
    public function dashboard_tes()
    {
        $this->load->view('tes');
    }
    public function dashboard_tes2()
    {
        $this->load->view('tes2');
    }
    public function dashboard_tes3()
    {
        $this->load->view('tes3');
    }
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */