<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Checkup_model extends CI_Model
{

    public $table = 'checkup';
    public $id = 'id_checkup';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_checkup,id_pasien,keluhan,hasil_tensi,suhu,hasil_analisa,sistol,distol,denyut_jantung,status');
        $this->datatables->from('checkup');
        //add this line for join
        //$this->datatables->join('table2', 'checkup.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('checkup/read/$1'),'Read')." | ".anchor(site_url('checkup/update/$1'),'Update')." | ".anchor(site_url('checkup/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_checkup');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_checkup', $q);
	$this->db->or_like('id_pasien', $q);
	$this->db->or_like('keluhan', $q);
	$this->db->or_like('hasil_tensi', $q);
	$this->db->or_like('suhu', $q);
	$this->db->or_like('hasil_analisa', $q);
	$this->db->or_like('sistol', $q);
	$this->db->or_like('distol', $q);
	$this->db->or_like('denyut_jantung', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_checkup', $q);
	$this->db->or_like('id_pasien', $q);
	$this->db->or_like('keluhan', $q);
	$this->db->or_like('hasil_tensi', $q);
	$this->db->or_like('suhu', $q);
	$this->db->or_like('hasil_analisa', $q);
	$this->db->or_like('sistol', $q);
	$this->db->or_like('distol', $q);
	$this->db->or_like('denyut_jantung', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Checkup_model.php */
/* Location: ./application/models/Checkup_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-24 00:42:22 */
/* http://harviacode.com */