<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class History_pasien_model extends CI_Model
{

    public $table = 'history_pasien';
    public $id = 'id_history';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_history,id_pasien,id_dokter,id_ruangan,jumlah_infus,ekg');
        $this->datatables->from('history_pasien');
        //add this line for join
        //$this->datatables->join('table2', 'history_pasien.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('history_pasien/read/$1'),'Read')." | ".anchor(site_url('history_pasien/update/$1'),'Update')." | ".anchor(site_url('history_pasien/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_history');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_history', $q);
	$this->db->or_like('id_pasien', $q);
	$this->db->or_like('id_dokter', $q);
	$this->db->or_like('id_ruangan', $q);
	$this->db->or_like('jumlah_infus', $q);
	$this->db->or_like('ekg', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_history', $q);
	$this->db->or_like('id_pasien', $q);
	$this->db->or_like('id_dokter', $q);
	$this->db->or_like('id_ruangan', $q);
	$this->db->or_like('jumlah_infus', $q);
	$this->db->or_like('ekg', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file History_pasien_model.php */
/* Location: ./application/models/History_pasien_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-24 00:42:22 */
/* http://harviacode.com */